### ISSUE TITLE
`os.remove`, `os.rename`, and `os.tmpname` replacement.

### ISSUE THREAD

**Issue by gphg** [2dengine/love.maker#1]
I found these are the problem that cause file not being written on Linux. I managed to get it writing the file by replace these with `love.filesystem`.

Also [zorg said on forum](https://love2d.org/forums/viewtopic.php?p=235908):
> As for lua itself, these would be best avoided:
> \- dofile, loadfile (not loadstring or load), the whole io library, os.remove, os.rename, os.tmpname -> due to the fact that paths can behave differently on different OS-es. one exception: with some editors, to have console output, you need to do io.setvbuf('no').

**Comment by 2dengine** [comment]
Hello and thank you for using the library. From what I remember the io. and os. modules work with absolute paths, whereas love.filesystem usually works with relative paths. Also, the io. module allows us to save/export .love files outside of the AppData directory which is important when automating your game distribution.
I have not tested the library on Linux, but will keep your suggestion in mind for the future.
Thank you again,
Ivan

**Comment by gphg** [comment]
> I have not tested the library on Linux, but will keep your suggestion in mind for the future.

There is a bug on Linux. I hope this can be fixed. I simply clone this repo, and run the example. I had to modify two lines to show the error.
```lua
local ok, err = build:save(dest, "DEMO") -- absolute path and comment/stamp
if not ok then
  return error(err)
end
```
The error:
```
Error: Could not open file /tmp/lua_cRqtDk (not found)
stack traceback:
        [love "boot.lua"]:345: in function <[love "boot.lua"]:341>
        [builtin#19]: at 0x716c39a25c
        [C]: in function 'require'
        [love "boot.lua"]:316: in function <[love "boot.lua"]:126>
        [C]: in function 'xpcall'
        [love "boot.lua"]:355: in function <[love "boot.lua"]:348>
        [C]: in function 'xpcall'
```

**Comment by 2dengine** [comment]
Hello, Sir. I have just pushed an update to the library and I can confirm that it now works on both Windows and Ubuntu. It looks like os.tmpname() returns "/tmp/XXXX" where the "tmp" directory is NOT present on many Linux distros including Ubuntu.
I will close this case after you confirm that it works.

**Comment by gphg** [comment]
I confirmed this works. Closing this case.

By the way, as this case hasn't been worked, I came with my own solution and it can be viewed here: https://gitgud.io/garett/gamedev-2022/-/blame/gaming/platform/src/Modules/maker/init.lua

**Comment by 2dengine** [comment]
Sir, regarding you solution of using `tostring({}):sub(10) -- psoudo-random hex`:
I am not 100% sure about tostring({}):sub(10) but it is probably not a good way to generate filenames. I considered using math.random too although that solutions has some issues too in terms of determinism. For example the math random seed could be the same when you run the app several times in a row resulting in the same filename.
os.tmpname with the gsub('/', '') modification is probably the most reliable way in regards to generating filenames.

**Comment by gphg** [comment]
Regarding that line of code in question. I'm quite aware and it was kinda bothering me, but I just "it is what it is" until I get better suggestions from someone more experienced than me. Also it would be deleted later on.

I have math random on main script and it takes `os.time`, see: https://gitgud.io/garett/gamedev-2022/-/blob/gaming/platform/src/main.lua#L1

I'll change that to `love.math.random`.

Thank you for the input.
